% This function should be merged into the solar_class
function out = call_SAM(CSP,PC)

    switch CSP.location
        case 'Imperial CA'
            location_path = 'data\imperial_ca_32.835205_-115.572398_psmv3_60_tmy.csv' ;
        otherwise
            error('Only Imperial CA specified so far')
    end

    % For large solar multiples, SAM is unlikely to execute without
    % problems. If the SM>2, then just run SAM with SM=2 and then scale up
    % the power outputs and losses appropriately
    if CSP.solar_multiple > 2
        SM = 2;
        fac = CSP.solar_multiple / 2;
    else
        SM = CSP.solar_multiple ;
        fac = 1;
    end

	ssccall('load');
	%disp('Current folder = C:/Users/jmcti/OneDrive/Documents/GeoHybrids_2022/RTES/GeoTES_TEA/SAM');
	%disp(sprintf('SSC Version = %d', ssccall('version')));
	%disp(sprintf('SSC Build Information = %s', ssccall('build_info')));
	ssccall('module_exec_set_print',0);
	data = ssccall('data_create');
	
    % Main inputs
    ssccall('data_set_string', data, 'file_name', location_path);
	ssccall('data_set_number', data, 'I_bn_des', CSP.nominal_DNI); %950
	ssccall('data_set_number', data, 'T_loop_in_des', CSP.Tmin); %300
	ssccall('data_set_number', data, 'T_loop_out', CSP.Tmax); %565
	ssccall('data_set_number', data, 'q_pb_design', PC.Qin0); %50
	ssccall('data_set_number', data, 'tshours', 6); % Best to leave this as 6, for complicated reasons
	ssccall('data_set_number', data, 'specified_solar_multiple', SM);%2
	ssccall('data_set_number', data, 'non_solar_field_land_area_multiplier', CSP.land_mult);%1.1

    % The MATLAB code auto-generated by SAM uses the number of loops nloops
    % that SAM automatically calculates to provide the right mirror area to
    % give the right thermal power output. If we want to vary the power
    % output or solar multiple, we need to re-calculate nloops. This
    % requires the automatic SAM calculation to be replicated here. The
    % calculation gathers various optical losses and thermal losses and
    % finds nloops to give the design power times solar multiple at the
    % nominal DNI.

    nSCA = 4 ; % Number of collectors (SCAs) per loop
    aperture_SCA = 656 ; % Aperture of a single collector, m2
    length_SCA = 115 ; % Length of a single collector, m

    % Collector optical efficiencies
    SCA_track = 0.988 ;
    SCA_general_optical = 1;
    SCA_geometry = 0.952 ;
    SCA_reflectance = 0.93 ;
    SCA_dirt = 0.97 ;
    SCA_optical_eff = SCA_track * SCA_general_optical * SCA_geometry * SCA_reflectance * SCA_dirt ;

    % Receiver (HCE) optical efficiencies
    HCE_absorbtance = 0.963;
    HCE_trans = 0.964 ;
    HCE_bellows = 0.935 ;
    HCE_dirt = 0.98 ;

    HCE_heat_loss = 190 ; % W/m

    HCE_optical_eff = HCE_absorbtance * HCE_trans * HCE_bellows * HCE_dirt ;

    loop_optical_eff = SCA_optical_eff * HCE_optical_eff ;

    % Design heat generated per loop
    Q_per_loop = CSP.nominal_DNI * aperture_SCA * nSCA * loop_optical_eff;

    % Heat loss per loop
    Qloss_per_loop = HCE_heat_loss * length_SCA * nSCA ;

    nloops = ceil(PC.Qin0 * SM * 1e6 / (Q_per_loop - Qloss_per_loop)) ;
    
    % Other default inputs
    ssccall('data_set_number', data, 'track_mode', 1);
	ssccall('data_set_number', data, 'tilt', 0);
	ssccall('data_set_number', data, 'azimuth', 0);
	ssccall('data_set_number', data, 'nSCA', nSCA);
	ssccall('data_set_number', data, 'nHCEt', nSCA);
	ssccall('data_set_number', data, 'nColt', nSCA);
	ssccall('data_set_number', data, 'nHCEVar', nSCA);
	ssccall('data_set_number', data, 'nLoops', nloops);
	ssccall('data_set_number', data, 'eta_pump', 0.84999999999999998);
	ssccall('data_set_number', data, 'HDR_rough', 4.57e-05);
	ssccall('data_set_number', data, 'theta_stow', 170);
	ssccall('data_set_number', data, 'theta_dep', 10);
	ssccall('data_set_number', data, 'Row_Distance', 15);
	ssccall('data_set_number', data, 'FieldConfig', 1);
	ssccall('data_set_number', data, 'is_model_heat_sink_piping', 0);
	ssccall('data_set_number', data, 'L_heat_sink_piping', 50);
	ssccall('data_set_number', data, 'm_dot_htfmin', 1);
	ssccall('data_set_number', data, 'm_dot_htfmax', 12);
	ssccall('data_set_number', data, 'Fluid', 18);
	ssccall('data_set_number', data, 'wind_stow_speed', 25);
	field_fl_props =[ 20   4.1799999999999997   999   0.001   9.9999999999999995e-07   0.58699999999999997   85.299999999999997 ; 40   4.1799999999999997   993   0.00065300000000000004   6.5799999999999999e-07   0.61799999999999999   169 ; 60   4.1799999999999997   984   0.00046700000000000002   4.75e-07   0.64200000000000002   252 ; 80   4.1900000000000004   972   0.00035500000000000001   3.65e-07   0.65700000000000003   336 ; 100   4.21   959   0.00028200000000000002   2.9400000000000001e-07   0.66600000000000004   420 ; 120   4.25   944   0.000233   2.4600000000000001e-07   0.67000000000000004   505 ; 140   4.2800000000000002   927   0.00019699999999999999   2.1199999999999999e-07   0.67000000000000004   590 ; 160   4.3399999999999999   908   0.00017100000000000001   1.8799999999999999e-07   0.66700000000000004   676 ; 180   4.4000000000000004   887   0.00014999999999999999   1.6899999999999999e-07   0.66100000000000003   764 ; 200   4.4900000000000002   865   0.000134   1.55e-07   0.65100000000000002   852 ; 220   4.5800000000000001   842   0.000118   1.4100000000000001e-07   0.64100000000000001   941 ];
	ssccall( 'data_set_matrix', data, 'field_fl_props', field_fl_props );
	ssccall('data_set_number', data, 'T_fp', 10);
	ssccall('data_set_number', data, 'Pipe_hl_coef', 0.45000000000000001);
	ssccall('data_set_number', data, 'SCA_drives_elec', 125);
	ssccall('data_set_number', data, 'water_usage_per_wash', 0.69999999999999996);
	ssccall('data_set_number', data, 'washing_frequency', 12);
	ssccall('data_set_number', data, 'accept_mode', 0);
	ssccall('data_set_number', data, 'accept_init', 0);
	ssccall('data_set_number', data, 'accept_loc', 1);
	ssccall('data_set_number', data, 'mc_bal_hot', 0.20000000000000001);
	ssccall('data_set_number', data, 'mc_bal_cold', 0.20000000000000001);
	ssccall('data_set_number', data, 'mc_bal_sca', 4.5);
	W_aperture =[ 6; 6; 6; 6 ];
	ssccall( 'data_set_array', data, 'W_aperture', W_aperture );
	A_aperture =[ aperture_SCA; aperture_SCA; aperture_SCA; aperture_SCA ];
	ssccall( 'data_set_array', data, 'A_aperture', A_aperture );
	TrackingError =[ SCA_track; SCA_track; SCA_track; SCA_track ];
	ssccall( 'data_set_array', data, 'TrackingError', TrackingError );
	GeomEffects =[ SCA_geometry; SCA_geometry; SCA_geometry; SCA_geometry ];
	ssccall( 'data_set_array', data, 'GeomEffects', GeomEffects );
	Rho_mirror_clean =[ SCA_reflectance; SCA_reflectance; SCA_reflectance; SCA_reflectance ];
	ssccall( 'data_set_array', data, 'Rho_mirror_clean', Rho_mirror_clean );
	Dirt_mirror =[ SCA_dirt; SCA_dirt; SCA_dirt; SCA_dirt ];
	ssccall( 'data_set_array', data, 'Dirt_mirror', Dirt_mirror );
	Error =[ SCA_general_optical; SCA_general_optical; SCA_general_optical; SCA_general_optical ];
	ssccall( 'data_set_array', data, 'Error', Error );
	Ave_Focal_Length =[ 2.1499999999999999; 2.1499999999999999; 2.1499999999999999; 2.1499999999999999 ];
	ssccall( 'data_set_array', data, 'Ave_Focal_Length', Ave_Focal_Length );
	L_SCA =[ length_SCA; length_SCA; length_SCA; length_SCA ];
	ssccall( 'data_set_array', data, 'L_SCA', L_SCA );
    nmod = 8;
	L_aperture =[ length_SCA/nmod; length_SCA/nmod; length_SCA/nmod; length_SCA/nmod ];
	ssccall( 'data_set_array', data, 'L_aperture', L_aperture );
	ColperSCA =[ nmod; nmod; nmod; nmod ];
	ssccall( 'data_set_array', data, 'ColperSCA', ColperSCA );
	Distance_SCA =[ 1; 1; 1; 1 ];
	ssccall( 'data_set_array', data, 'Distance_SCA', Distance_SCA );
	IAM_matrix =[ 1   0.0327   -0.1351 ; 1   0.0327   -0.1351 ; 1   0.0327   -0.1351 ; 1   0.0327   -0.1351 ];
	ssccall( 'data_set_matrix', data, 'IAM_matrix', IAM_matrix );
	HCE_FieldFrac =[ 1   0   0   0 ; 1   0   0   0 ; 1   0   0   0 ; 1   0   0   0 ];
	ssccall( 'data_set_matrix', data, 'HCE_FieldFrac', HCE_FieldFrac );
	D_2 =[ 0.075999999999999998   0.075999999999999998   0.075999999999999998   0.075999999999999998 ; 0.075999999999999998   0.075999999999999998   0.075999999999999998   0.075999999999999998 ; 0.075999999999999998   0.075999999999999998   0.075999999999999998   0.075999999999999998 ; 0.075999999999999998   0.075999999999999998   0.075999999999999998   0.075999999999999998 ];
	ssccall( 'data_set_matrix', data, 'D_2', D_2 );
	D_3 =[ 0.080000000000000002   0.080000000000000002   0.080000000000000002   0.080000000000000002 ; 0.080000000000000002   0.080000000000000002   0.080000000000000002   0.080000000000000002 ; 0.080000000000000002   0.080000000000000002   0.080000000000000002   0.080000000000000002 ; 0.080000000000000002   0.080000000000000002   0.080000000000000002   0.080000000000000002 ];
	ssccall( 'data_set_matrix', data, 'D_3', D_3 );
	D_4 =[ 0.115   0.115   0.115   0.115 ; 0.115   0.115   0.115   0.115 ; 0.115   0.115   0.115   0.115 ; 0.115   0.115   0.115   0.115 ];
	ssccall( 'data_set_matrix', data, 'D_4', D_4 );
	D_5 =[ 0.12   0.12   0.12   0.12 ; 0.12   0.12   0.12   0.12 ; 0.12   0.12   0.12   0.12 ; 0.12   0.12   0.12   0.12 ];
	ssccall( 'data_set_matrix', data, 'D_5', D_5 );
	D_p =[ 0   0   0   0 ; 0   0   0   0 ; 0   0   0   0 ; 0   0   0   0 ];
	ssccall( 'data_set_matrix', data, 'D_p', D_p );
	Flow_type =[ 1   1   1   1 ; 1   1   1   1 ; 1   1   1   1 ; 1   1   1   1 ];
	ssccall( 'data_set_matrix', data, 'Flow_type', Flow_type );
	Rough =[ 4.5000000000000003e-05   4.5000000000000003e-05   4.5000000000000003e-05   4.5000000000000003e-05 ; 4.5000000000000003e-05   4.5000000000000003e-05   4.5000000000000003e-05   4.5000000000000003e-05 ; 4.5000000000000003e-05   4.5000000000000003e-05   4.5000000000000003e-05   4.5000000000000003e-05 ; 4.5000000000000003e-05   4.5000000000000003e-05   4.5000000000000003e-05   4.5000000000000003e-05 ];
	ssccall( 'data_set_matrix', data, 'Rough', Rough );
	alpha_env =[ 0.02   0.02   0   0 ; 0.02   0.02   0   0 ; 0.02   0.02   0   0 ; 0.02   0.02   0   0 ];
	ssccall( 'data_set_matrix', data, 'alpha_env', alpha_env );
	epsilon_3_11 =[ 100   0.064000000000000001 ; 150   0.066500000000000004 ; 200   0.070000000000000007 ; 250   0.074499999999999997 ; 300   0.080000000000000002 ; 350   0.086499999999999994 ; 400   0.094 ; 450   0.10249999999999999 ; 500   0.112 ];
	ssccall( 'data_set_matrix', data, 'epsilon_3_11', epsilon_3_11 );
	epsilon_3_12 =[ 0.65000000000000002 ];
	ssccall( 'data_set_matrix', data, 'epsilon_3_12', epsilon_3_12 );
	epsilon_3_13 =[ 0.65000000000000002 ];
	ssccall( 'data_set_matrix', data, 'epsilon_3_13', epsilon_3_13 );
	epsilon_3_14 =[ 0 ];
	ssccall( 'data_set_matrix', data, 'epsilon_3_14', epsilon_3_14 );
	epsilon_3_21 =[ 100   0.064000000000000001 ; 150   0.066500000000000004 ; 200   0.070000000000000007 ; 250   0.074499999999999997 ; 300   0.080000000000000002 ; 350   0.086499999999999994 ; 400   0.094 ; 450   0.10249999999999999 ; 500   0.112 ];
	ssccall( 'data_set_matrix', data, 'epsilon_3_21', epsilon_3_21 );
	epsilon_3_22 =[ 0.65000000000000002 ];
	ssccall( 'data_set_matrix', data, 'epsilon_3_22', epsilon_3_22 );
	epsilon_3_23 =[ 0.65000000000000002 ];
	ssccall( 'data_set_matrix', data, 'epsilon_3_23', epsilon_3_23 );
	epsilon_3_24 =[ 0 ];
	ssccall( 'data_set_matrix', data, 'epsilon_3_24', epsilon_3_24 );
	epsilon_3_31 =[ 100   0.064000000000000001 ; 150   0.066500000000000004 ; 200   0.070000000000000007 ; 250   0.074499999999999997 ; 300   0.080000000000000002 ; 350   0.086499999999999994 ; 400   0.094 ; 450   0.10249999999999999 ; 500   0.112 ];
	ssccall( 'data_set_matrix', data, 'epsilon_3_31', epsilon_3_31 );
	epsilon_3_32 =[ 0.65000000000000002 ];
	ssccall( 'data_set_matrix', data, 'epsilon_3_32', epsilon_3_32 );
	epsilon_3_33 =[ 0.65000000000000002 ];
	ssccall( 'data_set_matrix', data, 'epsilon_3_33', epsilon_3_33 );
	epsilon_3_34 =[ 0 ];
	ssccall( 'data_set_matrix', data, 'epsilon_3_34', epsilon_3_34 );
	epsilon_3_41 =[ 100   0.064000000000000001 ; 150   0.066500000000000004 ; 200   0.070000000000000007 ; 250   0.074499999999999997 ; 300   0.080000000000000002 ; 350   0.086499999999999994 ; 400   0.094 ; 450   0.10249999999999999 ; 500   0.112 ];
	ssccall( 'data_set_matrix', data, 'epsilon_3_41', epsilon_3_41 );
	epsilon_3_42 =[ 0.65000000000000002 ];
	ssccall( 'data_set_matrix', data, 'epsilon_3_42', epsilon_3_42 );
	epsilon_3_43 =[ 0.65000000000000002 ];
	ssccall( 'data_set_matrix', data, 'epsilon_3_43', epsilon_3_43 );
	epsilon_3_44 =[ 0 ];
	ssccall( 'data_set_matrix', data, 'epsilon_3_44', epsilon_3_44 );
	alpha_abs =[ HCE_absorbtance   HCE_absorbtance   0.80000000000000004   0 ; HCE_absorbtance   HCE_absorbtance   0.80000000000000004   0 ; HCE_absorbtance   HCE_absorbtance   0.80000000000000004   0 ; HCE_absorbtance   HCE_absorbtance   0.80000000000000004   0 ];
	ssccall( 'data_set_matrix', data, 'alpha_abs', alpha_abs );
	Tau_envelope =[ HCE_trans   HCE_trans   1   0 ; HCE_trans   HCE_trans   1   0 ; HCE_trans   HCE_trans   1   0 ; HCE_trans   HCE_trans   1   0 ];
	ssccall( 'data_set_matrix', data, 'Tau_envelope', Tau_envelope );
	EPSILON_4 =[ 0.85999999999999999   0.85999999999999999   1   0 ; 0.85999999999999999   0.85999999999999999   1   0 ; 0.85999999999999999   0.85999999999999999   1   0 ; 0.85999999999999999   0.85999999999999999   1   0 ];
	ssccall( 'data_set_matrix', data, 'EPSILON_4', EPSILON_4 );
	EPSILON_5 =[ 0.85999999999999999   0.85999999999999999   1   0 ; 0.85999999999999999   0.85999999999999999   1   0 ; 0.85999999999999999   0.85999999999999999   1   0 ; 0.85999999999999999   0.85999999999999999   1   0 ];
	ssccall( 'data_set_matrix', data, 'EPSILON_5', EPSILON_5 );
	GlazingIntactIn =[ 1   1   0   1 ; 1   1   0   1 ; 1   1   0   1 ; 1   1   0   1 ];
	ssccall( 'data_set_matrix', data, 'GlazingIntactIn', GlazingIntactIn );
	P_a =[ 0.0001   750   750   0 ; 0.0001   750   750   0 ; 0.0001   750   750   0 ; 0.0001   750   750   0 ];
	ssccall( 'data_set_matrix', data, 'P_a', P_a );
	AnnulusGas =[ 27   1   1   1 ; 27   1   1   1 ; 27   1   1   27 ; 27   1   1   27 ];
	ssccall( 'data_set_matrix', data, 'AnnulusGas', AnnulusGas );
	AbsorberMaterial =[ 1   1   1   1 ; 1   1   1   1 ; 1   1   1   1 ; 1   1   1   1 ];
	ssccall( 'data_set_matrix', data, 'AbsorberMaterial', AbsorberMaterial );
	Shadowing =[ HCE_bellows   HCE_bellows   HCE_bellows   0.96299999999999997 ; HCE_bellows   HCE_bellows   HCE_bellows   0.96299999999999997 ; HCE_bellows  HCE_bellows   HCE_bellows   0.96299999999999997 ; HCE_bellows  HCE_bellows   HCE_bellows   0.96299999999999997 ];
	ssccall( 'data_set_matrix', data, 'Shadowing', Shadowing );
	Dirt_HCE =[ HCE_dirt   HCE_dirt   1   HCE_dirt ; HCE_dirt   HCE_dirt   1   HCE_dirt ; HCE_dirt   HCE_dirt   1   HCE_dirt ; HCE_dirt   HCE_dirt   1   HCE_dirt ];
	ssccall( 'data_set_matrix', data, 'Dirt_HCE', Dirt_HCE );
	Design_loss =[ HCE_heat_loss   1270   1500   0 ; HCE_heat_loss   1270   1500   0 ; HCE_heat_loss   1270   1500   0 ; HCE_heat_loss   1270   1500   0 ];
	ssccall( 'data_set_matrix', data, 'Design_loss', Design_loss );
	ssccall('data_set_number', data, 'pb_pump_coef', 0.55000000000000004);
	ssccall('data_set_number', data, 'init_hot_htf_percent', 30);
	ssccall('data_set_number', data, 'h_tank', 15);
	ssccall('data_set_number', data, 'cold_tank_max_heat', 0.5);
	ssccall('data_set_number', data, 'u_tank', 0.29999999999999999);
	ssccall('data_set_number', data, 'tank_pairs', 1);
	ssccall('data_set_number', data, 'cold_tank_Thtr', 60);
	ssccall('data_set_number', data, 'h_tank_min', 0.5);
	ssccall('data_set_number', data, 'hot_tank_Thtr', 110);
	ssccall('data_set_number', data, 'hot_tank_max_heat', 1);
	weekday_schedule =[ 6   6   6   6   6   6   5   5   4   4   4   4   4   4   4   4   4   4   4   4   4   5   5   5 ; 6   6   6   6   6   6   5   5   4   4   4   4   4   4   4   4   4   4   4   4   4   5   5   5 ; 6   6   6   6   6   6   5   5   4   4   4   4   4   4   4   4   4   4   4   4   4   5   5   5 ; 6   6   6   6   6   6   5   5   4   4   4   4   4   4   4   4   4   4   4   4   4   5   5   5 ; 6   6   6   6   6   6   5   5   4   4   4   4   4   4   4   4   4   4   4   4   4   5   5   5 ; 3   3   3   3   3   3   3   3   2   2   2   2   1   1   1   1   1   1   2   2   2   3   3   3 ; 3   3   3   3   3   3   3   3   2   2   2   2   1   1   1   1   1   1   2   2   2   3   3   3 ; 3   3   3   3   3   3   3   3   2   2   2   2   1   1   1   1   1   1   2   2   2   3   3   3 ; 3   3   3   3   3   3   3   3   2   2   2   2   1   1   1   1   1   1   2   2   2   3   3   3 ; 6   6   6   6   6   6   5   5   4   4   4   4   4   4   4   4   4   4   4   4   4   5   5   5 ; 6   6   6   6   6   6   5   5   4   4   4   4   4   4   4   4   4   4   4   4   4   5   5   5 ; 6   6   6   6   6   6   5   5   4   4   4   4   4   4   4   4   4   4   4   4   4   5   5   5 ];
	ssccall( 'data_set_matrix', data, 'weekday_schedule', weekday_schedule );
	weekend_schedule =[ 6   6   6   6   6   6   5   5   5   5   5   5   5   5   5   5   5   5   5   5   5   5   5   5 ; 6   6   6   6   6   6   5   5   5   5   5   5   5   5   5   5   5   5   5   5   5   5   5   5 ; 6   6   6   6   6   6   5   5   5   5   5   5   5   5   5   5   5   5   5   5   5   5   5   5 ; 6   6   6   6   6   6   5   5   5   5   5   5   5   5   5   5   5   5   5   5   5   5   5   5 ; 6   6   6   6   6   6   5   5   5   5   5   5   5   5   5   5   5   5   5   5   5   5   5   5 ; 3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3 ; 3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3 ; 3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3 ; 3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3 ; 6   6   6   6   6   6   5   5   5   5   5   5   5   5   5   5   5   5   5   5   5   5   5   5 ; 6   6   6   6   6   6   5   5   5   5   5   5   5   5   5   5   5   5   5   5   5   5   5   5 ; 6   6   6   6   6   6   5   5   5   5   5   5   5   5   5   5   5   5   5   5   5   5   5   5 ];
	ssccall( 'data_set_matrix', data, 'weekend_schedule', weekend_schedule );
	ssccall('data_set_number', data, 'is_tod_pc_target_also_pc_max', 0);
	ssccall('data_set_number', data, 'is_dispatch', 0);
	ssccall('data_set_number', data, 'disp_frequency', 24);
	ssccall('data_set_number', data, 'disp_horizon', 48);
	ssccall('data_set_number', data, 'disp_max_iter', 35000);
	ssccall('data_set_number', data, 'disp_timeout', 5);
	ssccall('data_set_number', data, 'disp_mip_gap', 0.001);
	ssccall('data_set_number', data, 'disp_time_weighting', 0.98999999999999999);
	ssccall('data_set_number', data, 'disp_rsu_cost_rel', 952);
	ssccall('data_set_number', data, 'disp_csu_cost_rel', 87);
	ssccall('data_set_number', data, 'disp_pen_ramping', 1);
	ssccall('data_set_number', data, 'is_wlim_series', 0);
	wlim_series = csvread( 'C:/Users/jmcti/OneDrive/Documents/GeoHybrids_2022/RTES/GeoTES_TEA/SAM/wlim_series.csv');
	ssccall( 'data_set_array', data, 'wlim_series', wlim_series );
	f_turb_tou_periods =[ 1.05; 1; 1; 1; 1; 1; 1; 1; 1 ];
	ssccall( 'data_set_array', data, 'f_turb_tou_periods', f_turb_tou_periods );
	ssccall('data_set_number', data, 'is_dispatch_series', 0);
	dispatch_series =[ 0 ];
	ssccall( 'data_set_array', data, 'dispatch_series', dispatch_series );
	ssccall('data_set_number', data, 'pb_fixed_par', 0.0054999999999999997);
	bop_array =[ 0; 1; 0; 0.48299999999999998; 0 ];
	ssccall( 'data_set_array', data, 'bop_array', bop_array );
	aux_array =[ 0.023; 1; 0.48299999999999998; 0.57099999999999995; 0 ];
	ssccall( 'data_set_array', data, 'aux_array', aux_array );
	ssccall('data_set_number', data, 'calc_design_pipe_vals', 1);
	ssccall('data_set_number', data, 'V_hdr_cold_max', 3);
	ssccall('data_set_number', data, 'V_hdr_cold_min', 2);
	ssccall('data_set_number', data, 'V_hdr_hot_max', 3);
	ssccall('data_set_number', data, 'V_hdr_hot_min', 2);
	ssccall('data_set_number', data, 'N_max_hdr_diams', 10);
	ssccall('data_set_number', data, 'L_rnr_pb', 25);
	ssccall('data_set_number', data, 'L_rnr_per_xpan', 70);
	ssccall('data_set_number', data, 'L_xpan_hdr', 20);
	ssccall('data_set_number', data, 'L_xpan_rnr', 20);
	ssccall('data_set_number', data, 'Min_rnr_xpans', 1);
	ssccall('data_set_number', data, 'northsouth_field_sep', 20);
	ssccall('data_set_number', data, 'N_hdr_per_xpan', 2);
	ssccall('data_set_number', data, 'offset_xpan_hdr', 1);
	K_cpnt =[ 0.90000000000000002   0   0.19   0   0.90000000000000002   -1   -1   -1   -1   -1   -1 ; 0   0.59999999999999998   0.050000000000000003   0   0.59999999999999998   0   0.59999999999999998   0   0.41999999999999998   0   0.14999999999999999 ; 0.050000000000000003   0   0.41999999999999998   0   0.59999999999999998   0   0.59999999999999998   0   0.41999999999999998   0   0.14999999999999999 ; 0.050000000000000003   0   0.41999999999999998   0   0.59999999999999998   0   0.59999999999999998   0   0.41999999999999998   0   0.14999999999999999 ; 0.050000000000000003   0   0.41999999999999998   0   0.59999999999999998   0   0.59999999999999998   0   0.41999999999999998   0   0.14999999999999999 ; 0.050000000000000003   0   0.41999999999999998   0   0.59999999999999998   0   0.59999999999999998   0   0.14999999999999999   0.59999999999999998   0 ; 0.90000000000000002   0   0.19   0   0.90000000000000002   -1   -1   -1   -1   -1   -1 ];
	ssccall( 'data_set_matrix', data, 'K_cpnt', K_cpnt );
	D_cpnt =[ 0.085000000000000006   0.063500000000000001   0.085000000000000006   0.063500000000000001   0.085000000000000006   -1   -1   -1   -1   -1   -1 ; 0.085000000000000006   0.085000000000000006   0.085000000000000006   0.063500000000000001   0.063500000000000001   0.063500000000000001   0.063500000000000001   0.063500000000000001   0.063500000000000001   0.063500000000000001   0.085000000000000006 ; 0.085000000000000006   0.063500000000000001   0.063500000000000001   0.063500000000000001   0.063500000000000001   0.063500000000000001   0.063500000000000001   0.063500000000000001   0.063500000000000001   0.063500000000000001   0.085000000000000006 ; 0.085000000000000006   0.063500000000000001   0.063500000000000001   0.063500000000000001   0.063500000000000001   0.063500000000000001   0.063500000000000001   0.063500000000000001   0.063500000000000001   0.063500000000000001   0.085000000000000006 ; 0.085000000000000006   0.063500000000000001   0.063500000000000001   0.063500000000000001   0.063500000000000001   0.063500000000000001   0.063500000000000001   0.063500000000000001   0.063500000000000001   0.063500000000000001   0.085000000000000006 ; 0.085000000000000006   0.063500000000000001   0.063500000000000001   0.063500000000000001   0.063500000000000001   0.063500000000000001   0.063500000000000001   0.063500000000000001   0.085000000000000006   0.085000000000000006   0.085000000000000006 ; 0.085000000000000006   0.063500000000000001   0.085000000000000006   0.063500000000000001   0.085000000000000006   -1   -1   -1   -1   -1   -1 ];
	ssccall( 'data_set_matrix', data, 'D_cpnt', D_cpnt );
	L_cpnt =[ 0   0   0   0   0   -1   -1   -1   -1   -1   -1 ; 0   0   0   1   0   0   0   1   0   1   0 ; 0   1   0   1   0   0   0   1   0   1   0 ; 0   1   0   1   0   0   0   1   0   1   0 ; 0   1   0   1   0   0   0   1   0   1   0 ; 0   1   0   1   0   0   0   1   0   0   0 ; 0   0   0   0   0   -1   -1   -1   -1   -1   -1 ];
	ssccall( 'data_set_matrix', data, 'L_cpnt', L_cpnt );
	Type_cpnt =[ 0   1   0   1   0   -1   -1   -1   -1   -1   -1 ; 1   0   0   2   0   1   0   2   0   2   0 ; 0   2   0   2   0   1   0   2   0   2   0 ; 0   2   0   2   0   1   0   2   0   2   0 ; 0   2   0   2   0   1   0   2   0   2   0 ; 0   2   0   2   0   1   0   2   0   0   1 ; 0   1   0   1   0   -1   -1   -1   -1   -1   -1 ];
	ssccall( 'data_set_matrix', data, 'Type_cpnt', Type_cpnt );
	ssccall('data_set_number', data, 'custom_sf_pipe_sizes', 0);
	sf_rnr_diams =[ -1 ];
	ssccall( 'data_set_matrix', data, 'sf_rnr_diams', sf_rnr_diams );
	sf_rnr_wallthicks =[ -1 ];
	ssccall( 'data_set_matrix', data, 'sf_rnr_wallthicks', sf_rnr_wallthicks );
	sf_rnr_lengths =[ -1 ];
	ssccall( 'data_set_matrix', data, 'sf_rnr_lengths', sf_rnr_lengths );
	sf_hdr_diams =[ -1 ];
	ssccall( 'data_set_matrix', data, 'sf_hdr_diams', sf_hdr_diams );
	sf_hdr_wallthicks =[ -1 ];
	ssccall( 'data_set_matrix', data, 'sf_hdr_wallthicks', sf_hdr_wallthicks );
	sf_hdr_lengths =[ -1 ];
	ssccall( 'data_set_matrix', data, 'sf_hdr_lengths', sf_hdr_lengths );
	ssccall('data_set_number', data, 'tanks_in_parallel', 1);
	trough_loop_control =[ 4; 1; 1; 4; 1; 1; 3; 1; 1; 2; 1; 1; 1 ];
	ssccall( 'data_set_array', data, 'trough_loop_control', trough_loop_control );
	ssccall('data_set_number', data, 'disp_wlim_maxspec', 9.9999999999999998e+37);
	ssccall('data_set_number', data, 'adjust:constant', 4);
	
    % Call SAM via ssc
    module = ssccall('module_create', 'trough_physical_process_heat'); 
	ok = ssccall('module_exec', module, data);
	if ~ok,
		disp('trough_physical_process_heat errors:'); 
		ii=0;
		while 1,
			err = ssccall('module_log', module, ii);
			if strcmp(err,''),
			      break;
			end
			disp( err );
			ii=ii+1;
		end
		return 
	end
	
    ssccall('module_free', module);
	
    % Outputs
    %{
    annual_energy = ssccall('data_get_number', data, 'annual_energy' );
	disp(sprintf('%s = %g', 'Annual energy (year 1)', annual_energy));
	annual_gross_energy = ssccall('data_get_number', data, 'annual_gross_energy' );
	disp(sprintf('%s = %g', 'Annual gross energy (year 1)', annual_gross_energy));
	annual_thermal_consumption = ssccall('data_get_number', data, 'annual_thermal_consumption' );
	disp(sprintf('%s = %g', 'Annual thermal freeze protection (year 1)', annual_thermal_consumption));
	capacity_factor = ssccall('data_get_number', data, 'capacity_factor' );
	disp(sprintf('%s = %g', 'Capacity factor', capacity_factor));
	annual_electricity_consumption = ssccall('data_get_number', data, 'annual_electricity_consumption' );
	disp(sprintf('%s = %g', 'Annual electricity load (year 1)', annual_electricity_consumption));
    %}
    
    out.field_optical_eff = ssccall('data_get_array', data, 'EqOpteff' ) ;
    out.field_thermal_power = fac * ssccall('data_get_array', data, 'q_dot_htf_sf_out' ) ;
    out.field_Tinlet = ssccall('data_get_array', data, 'T_field_cold_in' ) ;
    out.field_Toutlet = ssccall('data_get_array', data, 'T_field_hot_out' ) ;
    out.field_mdot = fac * ssccall('data_get_array', data, 'm_dot_field_delivered' ) ;

    field_track_pow = fac * ssccall('data_get_array', data, 'W_dot_sca_track' ) ;
    field_HTF_pump_pow = fac * ssccall('data_get_array', data, 'W_dot_field_pump' ) ;

    out.field_elec_parasitics = field_track_pow + field_HTF_pump_pow ; % MW-e

    out.actual_SM = fac * ssccall('data_get_number', data, 'solar_multiple_actual' );

    out.DNI = ssccall('data_get_array', data, 'beam' ) ;
    out.Tamb = ssccall('data_get_array', data, 'twet' ) ;

    out.mirror_area = fac * nSCA * aperture_SCA * nloops ;
    out.land_area = out.mirror_area * CSP.land_mult;
    out.nominal_eff = loop_optical_eff ;
    out.annual_eff  = mean(out.field_optical_eff(out.field_optical_eff>0)) ;

    % Finish up
	ssccall('data_free', data);
	ssccall('unload');
end